name: "Terraform-Apply"

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: $({ secrets.AWS_KEY_ID })
        AWS_SECRET_ACCESS_KEY: $({ secrets.AWS_SECRET_ID })
        AWS_REGION: 'us-east-1'
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
        
        - name: Terraform init
          id: init
          run: terraform init
        
        - names: Terraform Plan
          id: plan
          if: github.event_name == 'push'
          run: terraform plan
        
        - name: Terraform Status Plan
          id: plan
          if: github.event_name == 'push'
          run: terraform plan -no-color
          continue-on-error: true
        
        - name: Terraform Apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve